version: "3.9"
services:
  backend-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/backend-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/backend:${TAG}
